oak:
  ros__parameters:
    camera:
      i_mx_id: "1844301051345D0E00"
      i_nn_type: none
      i_pipeline_type: RGBD
    rgb:
      i_resolution: '720'
      i_fps: 10.0
      i_low_bandwidth: true
    left:
      i_resolution: '400'
      i_fps: 10.0
      i_low_bandwidth: true
    right:
      i_resolution: '400'
      i_fps: 10.0
      i_low_bandwidth: true
    stereo:
      i_fps: 10.0
      i_low_bandwidth: true
